### ISSUE TITLE
The plugin doesn't work.

### ISSUE THREAD

**Issue by Spontini** [AnvilPowered/OnTime#1]
First of all, finally and thank you for making a rankup plugin, other ones were really outdated and out of support.

This is what i get everytime i try to run any kind of `/OT` command.
```
[15:32:12] [Server thread/INFO] [nucleus]: Spontini ran the command: /ot check
[15:32:12] [ForkJoinPool.commonPool-worker-6/INFO] [org.reflections.Reflections]: Reflections took 0 ms to scan 1 urls, producing 5 keys and 6 values
```

**Comment by alexstaeding** [comment]
Can you provide some more information?
1) What platform are you using the plugin on (Sponge/Spigot/Velocity)
2) Are you using Xodus or MongoDB?
3) Is there any output to the user who runs the command?

Could you also send the entire log if possible please.

**Comment by Spontini** [comment]
> Can you provide some more information?
> 
> 1. What platform are you using the plugin on (Sponge/Spigot/Velocity)
> 2. Are you using Xodus or MongoDB?
> 3. Is there any output to the user who runs the command?
> 
> Could you also send the entire log if possible please.

I didn't know this plugin a thing in spigot, i'm sorry.

I'm running in sponge version, i'm using Xodus and no there is zero output, there is a output only in console itself.

**Comment by alexstaeding** [comment]
Please update Anvil to https://ore.spongepowered.org/AnvilPowered/Anvil/versions/0.1.2
Also note that in order to set the time, you need to use inputs like `5h 20m` or `50s`.
`y` or `Y` = year
`M` = month
`d` or `D` = day
`h` or `H` = hour
`m` = minute
`s` = second

**Comment by Spontini** [comment]
> Please update Anvil to https://ore.spongepowered.org/AnvilPowered/Anvil/versions/0.1.2
> Also note that in order to set the time, you need to use inputs like `5h 20m` or `50s`.
> `y` or `Y` = year
> `M` = month
> `d` or `D` = day
> `h` or `H` = hour
> `m` = minute
> `s` = second

Thank you
